// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EF.Data.Models.DB
{
    public partial class TblAccount
    {
        public TblAccount()
        {
            TblLedger = new HashSet<TblLedger>();
        }

        public int Id { get; set; }
        public string BankName { get; set; }
        public string BankLocation { get; set; }
        public string Notes { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public decimal Balance { get; set; }
        public bool? PrimaryAccount { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ICollection<TblLedger> TblLedger { get; set; }
    }
}