// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EF.Data.Models.DB
{
    public partial class TblBillExpense
    {
        public TblBillExpense()
        {
            TblLedger = new HashSet<TblLedger>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Payment { get; set; }
        public string Notes { get; set; }
        public decimal Balance { get; set; }
        public DateTime PaymentDateDue { get; set; }
        public int PaymentDayDue { get; set; }
        public bool HasBalance { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ICollection<TblLedger> TblLedger { get; set; }
    }
}