// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF.Data.Models.DB
{
    public partial class tbl_AccountLedger
    {
        public int Id { get; set; }
        public int ExpenseId { get; set; }
        public int AccountId { get; set; }
        public string Notes { get; set; }
        public decimal AccountNewBalance { get; set; }
        public DateTime TransactionDate { get; set; }
        public string TransactionDescription { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual tbl_Account Account { get; set; }
    }
}