// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF.Data.Models.DB
{
    public partial class tbl_ExpenseType
    {
        public tbl_ExpenseType()
        {
            tbl_Expense = new HashSet<tbl_Expense>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ICollection<tbl_Expense> tbl_Expense { get; set; }
    }
}