// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF.Data.Models.DB
{
    public partial class tbl_ExpenseBalance
    {
        public int Id { get; set; }
        public int ExpenseId { get; set; }
        public decimal Balance { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime DateLastPaid { get; set; }
        public DateTime NextDueDate { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}