// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF.Data.Models.DB
{
    public partial class tbl_Account
    {
        public tbl_Account()
        {
            tbl_AccountLedger = new HashSet<tbl_AccountLedger>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal? Balance { get; set; }
        public string Notes { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ICollection<tbl_AccountLedger> tbl_AccountLedger { get; set; }
    }
}